// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb6WQfGsY84bblWUIcJEns6QH_W_1tcF0',
    appId: '1:5775535797:web:23fdc15e3ff6fd165ed8fc',
    messagingSenderId: '5775535797',
    projectId: 'clone-60f68',
    authDomain: 'clone-60f68.firebaseapp.com',
    storageBucket: 'clone-60f68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCNMAtlCnloFTQn1BXQms1e_bzzE7yyI',
    appId: '1:5775535797:android:385afb120f8cea025ed8fc',
    messagingSenderId: '5775535797',
    projectId: 'clone-60f68',
    storageBucket: 'clone-60f68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASxRy0ccx3860fSPIk_RZeTMM0KwTxlk0',
    appId: '1:5775535797:ios:70336101846dd3fe5ed8fc',
    messagingSenderId: '5775535797',
    projectId: 'clone-60f68',
    storageBucket: 'clone-60f68.appspot.com',
    iosBundleId: 'com.example.amazonepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASxRy0ccx3860fSPIk_RZeTMM0KwTxlk0',
    appId: '1:5775535797:ios:70336101846dd3fe5ed8fc',
    messagingSenderId: '5775535797',
    projectId: 'clone-60f68',
    storageBucket: 'clone-60f68.appspot.com',
    iosBundleId: 'com.example.amazonepro',
  );
}
